name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout code
      - uses: actions/checkout@v3

      # Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'

      # Install dependencies
      - name: Install dependencies
        run: npm ci

      # Build the project
      - name: Build
        run: npm run build

      # Deploy to GitHub Pages
      - name: Deploy
        run: |
          rm -rf ./node_modules
          mv dist/* .  # Move build files to root
          rm -rf dist
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add -A
          git commit -m "deploy: build and deploy to GitHub Pages" || echo "No changes to commit"
          git push https://x-access-token:${{ secrets.PORTFOLIO_PAT }}@github.com/minnbanya/minnbanya.github.io.git main
